In [1]:
import pandas as pd

### setting currenct working directory

In [6]:
import os
os.chdir("B:/Amith Mentorship")

In [7]:
ipl = pd.read_csv("iplfinal.csv", sep='|')

In [9]:
ipl.head()  ## first 6 rows

,match_description,match_date,match_venue,match_location,match_result,team_name,innings_order,batsman_name,dismissal_mode,runs,balls,fours,sixes
0,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Rohit Sharma (c),c Rayudu b Watson,15,18,1,1
1,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Evin Lewis,lbw b D Chahar,0,2,0,0
2,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Ishan Kishan (wk),c Mark Wood b Tahir,40,29,4,1
3,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Suryakumar Yadav,c Harbhajan b Watson,43,29,6,1
4,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Hardik Pandya,not out,22,20,2,0

In [82]:
#1 what is the maximum score of IPL 2018 and who scored it?
print(ipl[['batsman_name', 'runs']][ipl.runs == ipl.runs.max()])

          batsman_name  runs
680  Rishabh Pant (wk)   128

In [75]:
#2 how many centuries were hit in IPL 2018?
ipl[ipl['runs'] >=100].count()['runs']

5

In [83]:
# creating and adding strike rate column to the data frame
ipl['strike rate'] = (ipl['runs']/ ipl['balls'])*100

In [81]:
# checking whether the strike rate column is added to data frame or not
ipl.head()

,match_description,match_date,match_venue,match_location,match_result,team_name,innings_order,batsman_name,dismissal_mode,runs,balls,fours,sixes,strike rate
0,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Rohit Sharma (c),c Rayudu b Watson,15,18,1,1,83.333333
1,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Evin Lewis,lbw b D Chahar,0,2,0,0,0.000000
2,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Ishan Kishan (wk),c Mark Wood b Tahir,40,29,4,1,137.931034
3,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Suryakumar Yadav,c Harbhajan b Watson,43,29,6,1,148.275862
4,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Hardik Pandya,not out,22,20,2,0,110.000000

In [80]:
#3 list down the century makers, their scores and their strike rates
ipl[['batsman_name', 'runs', 'strike rate']][ipl['runs']>= 100]

          batsman_name  runs  strike rate
274        Chris Gayle   104   165.079365
285       Shane Watson   106   185.964912
680  Rishabh Pant (wk)   128   203.174603
739      Ambati Rayudu   100   161.290323
959       Shane Watson   117   205.263158

In [74]:
#6 what are the total number of duck dismissals?
ipl[ipl['runs'] ==0].count()['runs']

103

In [88]:
# Creating Boundary Percentage field
ipl['boundary %'] = (((4*ipl['fours'])+(6*ipl['sixes']))/ipl['runs'])*100

In [89]:
# Checking whether Boundary % field is created or not
ipl.head()

,match_description,match_date,match_venue,match_location,match_result,team_name,innings_order,batsman_name,dismissal_mode,runs,balls,fours,sixes,strike rate,boundary %
0,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Rohit Sharma (c),c Rayudu b Watson,15,18,1,1,83.333333,66.666667
1,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Evin Lewis,lbw b D Chahar,0,2,0,0,0.000000,NaN
2,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Ishan Kishan (wk),c Mark Wood b Tahir,40,29,4,1,137.931034,55.000000
3,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Suryakumar Yadav,c Harbhajan b Watson,43,29,6,1,148.275862,69.767442
4,"Mumbai Indians vs Chennai Super Kings, 1st Mat...",2018-04-07,"Wankhede Stadium,",Mumbai,Chennai Super Kings won by 1 wkt,Mumbai Indians Innings,innings_1,Hardik Pandya,not out,22,20,2,0,110.000000,36.363636

In [97]:
# lit top 5 players by contribution of boundaries to total scores
ipl.nlargest(5,{'boundary %'},keep = 'first')

,match_description,match_date,match_venue,match_location,match_result,team_name,innings_order,batsman_name,dismissal_mode,runs,balls,fours,sixes,strike rate,boundary %
32,Kolkata Knight Riders vs Royal Challengers Ban...,2018-04-08,"Eden Gardens,",Kolkata,Kolkata Knight Riders won by 4 wkts,Royal Challengers Bangalore Innings,innings_1,Quinton de Kock (wk),c Vinay Kumar b Chawla,4,4,1,0,100.0,100.0
62,Kolkata Knight Riders vs Royal Challengers Ban...,2018-04-08,"Eden Gardens,",Kolkata,Kolkata Knight Riders won by 4 wkts,Royal Challengers Bangalore Innings,innings_1,Quinton de Kock (wk),c Vinay Kumar b Chawla,4,4,1,0,100.0,100.0
78,"Sunrisers Hyderabad vs Rajasthan Royals, 4th M...",2018-04-09,"Rajiv Gandhi International Stadium,",Hyderabad,Sunrisers Hyderabad won by 9 wkts,Rajasthan Royals Innings,innings_1,D Arcy Short,run out (Williamson),4,4,1,0,100.0,100.0
92,"Chennai Super Kings vs Kolkata Knight Riders, ...",2018-04-10,"MA Chidambaram Stadium,",Chennai,Chennai Super Kings won by 5 wkts,Kolkata Knight Riders Innings,innings_1,Sunil Narine,c Raina b Harbhajan,12,4,0,2,300.0,100.0
143,Royal Challengers Bangalore vs Kings XI Punjab...,2018-04-13,"M.Chinnaswamy Stadium,",Bengaluru,Royal Challengers Bangalore won by 4 wkts,Kings XI Punjab Innings,innings_1,Yuvraj Singh,b Umesh,4,4,1,0,100.0,100.0